# 
# policy_path: "/home/conang/quadruped/unitree_rl_gym/logs/rough_go2/exported/policies/policy_1.pt"
policy_path: "/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/go2/policies/policy_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2_scene/scene.xml"

# Total simulation time
simulation_duration: 20.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

# default_angles: [0.1,  0.1,  -0.1,  -0.1, 0.8, 1.0, 
#                   0.8,  1.0,  -1.5,  -1.5, -1.5, -1.5]
# default_angles: [-1.5, 0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 1.0, -1.5, -0.1, 1.0]
default_angles: [0.1, 0.8, -1.5, 
                 -0.1, 0.8,-1.5,
                  0.1, 1.0,-1.5,
                  -0.1, 1.0,-1.5]         
# default_angles: [0.00571868, 0.608813, -1.21763, 
#                 -0.00571868, 0.608813, -1.21763,
#                 0.00571868, 0.608813, -1.21763, 
#                 -0.00571868, 0.608813, -1.21763]

# joint sequence
# 'FL_hip_joint', 'FL_thigh_joint', 'FL_calf_joint', 
# 'FR_hip_joint', 'FR_thigh_joint', 'FR_calf_joint',
# 'RL_hip_joint', 'RL_thigh_joint', 'RL_calf_joint',
# 'RR_hip_joint', 'RR_thigh_joint', 'RR_calf_joint'

# 'FL_calf_joint': -1.5,   # [rad]
# 'FL_hip_joint': 0.1,   # [rad]
# 'FL_thigh_joint': 0.8,     # [rad]

# 'FR_calf_joint': -1.5,  # [rad]
# 'FR_hip_joint': -0.1 ,  # [rad]
# 'FR_thigh_joint': 0.8,     # [rad]

# 'RL_calf_joint': -1.5,    # [rad]
# 'RL_hip_joint': 0.1,   # [rad]
# 'RL_thigh_joint': 1.,   # [rad]

# 'RR_calf_joint': -1.5,
# 'RR_hip_joint': -0.1,   # [rad]
# 'RR_thigh_joint': 1.,   # [rad]


lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 48

cmd_init: [0.5, 0.0, 0.0]