# 
policy_path: "/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/go2/policies/policy_0429.pt"
# policy_path: "/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/go2/policies/policy_7.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2_scene/scene.xml"

# Total simulation time
simulation_duration: 20.0
# Simulation time step
simulation_dt: 0.002 # 0.005   0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10 # 4    10

kps: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

new_seq: [3, 4, 5, 0, 1 , 2, 9, 10, 11, 6, 7, 8]

default_angles: [0.1, 0.8, -1.5, 
                 -0.1, 0.8,-1.5,
                  0.1, 1.0,-1.5,
                  -0.1, 1.0,-1.5]         

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 48

cmd_init: [0.5,0.0,0.0]